export const darkTheme = {
  id: 'dark',
  name: 'Dark Theme',
  desktop: 'bg-black',
  taskbar: 'bg-black/80 border-t border-white',
  window: { bg: 'bg-black', border: 'border-white', header: 'bg-black border-b border-white', text: 'text-white', content: 'text-white bg-black' },
  startMenu: 'bg-black border border-white',
  glass: 'bg-black/50 border border-white',
  text: { primary: 'text-white', secondary: 'text-gray-200', window: 'text-white', startMenu: 'text-white' },
  app: {
    bg: 'bg-black',
    text: 'text-white',
    input: 'bg-black border-white text-white placeholder-gray-300',
    button: 'bg-black hover:bg-white text-white hover:text-black border border-white',
    table: 'bg-black border-white',
    tableHeader: 'bg-black text-white',
    tableCell: 'bg-black text-white border-white',
    toolbar: 'bg-black border-b border-white',
    toolbarButton: 'text-white hover:bg-yellow-400 hover:text-black',
    paper_bg: 'bg-black',
    badge: 'bg-gray-500 text-gray-200',
    button_subtle_hover: 'hover:bg-gray-800',
    text_subtle: 'text-gray-300',
    dropdown_bg: 'bg-black border border-white',
    dropdown_item_hover: 'hover:bg-yellow-400 hover:text-black',
    toolbar_button_active: 'bg-yellow-400 text-black',
  },
  notification: 'bg-black text-white border border-white'
};